# Generated by Django 6.0.5 on 2026-06-01 10:18

import django.db.models.deletion
import spa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to=spa.models._avatar_path)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('theme', models.CharField(choices=[('system', 'Follow system'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=6)),
                ('contrast', models.CharField(choices=[('normal', 'Normal'), ('high', 'High contrast')], default='normal', max_length=6)),
                ('email_reminders', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
