# Generated by Django 6.0.7 on 2026-07-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityprofile',
            name='letter_focus',
            field=models.CharField(choices=[('soft_skill', 'Soft-skill focus'), ('balanced', 'Balanced'), ('technical', 'Technical focus')], default='balanced', max_length=16),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='letter_tone',
            field=models.CharField(choices=[('personal', 'Personal'), ('neutral', 'Neutral'), ('formal', 'Formal')], default='neutral', max_length=16),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='sample_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='style_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='style_dossier',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='writing_sample',
            field=models.TextField(blank=True),
        ),
    ]
