# Generated by Django 6.0.7 on 2026-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_personalityprofile_letter_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, upload_to='signatures'),
        ),
    ]
