# Generated by Django 6.0.7 on 2026-07-27 11:22

import django.db.models.deletion
import spa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0005_jobapplication_attachments_cvattachment_and_more'),
        ('spa', '0003_userprofile_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=spa.models._block_image_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('favourite', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(blank=True, related_name='portfolio_blocks', to='jac.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('application', 'Application')], default='manual', max_length=12)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_links', to='jac.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='spa.portfoliolink')),
            ],
        ),
        migrations.AddConstraint(
            model_name='portfoliolink',
            constraint=models.UniqueConstraint(condition=models.Q(('application__isnull', False), ('revoked_at__isnull', True)), fields=('application',), name='one_active_link_per_application'),
        ),
        migrations.AddConstraint(
            model_name='portfoliovisit',
            constraint=models.UniqueConstraint(fields=('link', 'day'), name='one_visit_row_per_link_day'),
        ),
    ]
