# Generated by Django 6.0.5 on 2026-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_personalityprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_socials',
            field=models.BooleanField(default=False),
        ),
    ]
