# Generated by Django 6.0.7 on 2026-07-30 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0005_jobapplication_attachments_cvattachment_and_more'),
        ('spa', '0004_portfolioblock_portfoliolink_portfoliovisit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliolink',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='portfoliolink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('revoked_at__isnull', True)), fields=('user',), name='one_default_link_per_user'),
        ),
    ]
