# Generated by Django 6.0.7 on 2026-08-01 19:59

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_handles(apps, schema_editor):
    """Give every existing profile a unique, DNS-safe handle before uniqueness is
    enforced. Seeded from the username, deduped against handles already assigned in
    this run (existing rows are still NULL at this point)."""
    UserProfile = apps.get_model("spa", "UserProfile")
    taken: set[str] = set()
    for p in UserProfile.objects.select_related("user").all():
        base = slugify(p.user.username)[:40].strip("-") or "user"
        cand, n = base, 2
        while cand in taken:
            suffix = f"-{n}"
            cand = f"{base[: 40 - len(suffix)]}{suffix}"
            n += 1
        p.handle = cand
        p.save(update_fields=["handle"])
        taken.add(cand)


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0005_jobapplication_attachments_cvattachment_and_more'),
        ('spa', '0005_portfoliolink_is_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add nullable first: existing rows get NULL (no unique clash), then the
        # backfill fills them, then uniqueness is turned on.
        migrations.AddField(
            model_name='userprofile',
            name='handle',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
        migrations.RunPython(backfill_handles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='handle',
            field=models.SlugField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliolink',
            name='slug',
            field=models.SlugField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='portfoliolink',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'slug'), name='unique_active_slug_per_user'),
        ),
    ]
