# Generated by Django 6.0.7 on 2026-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_userprofile_handle_alter_portfoliolink_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioblock',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
