# Generated by Django 6.0.5 on 2026-05-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skills_used',
            new_name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='jac.skill'),
        ),
        migrations.AddField(
            model_name='language',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jac.certification'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft'), ('domain', 'Domain / Industry'), ('other', 'Other')], default='technical', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jac.certification'),
        ),
    ]
