# Generated by Django 6.0.7 on 2026-07-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
