# Generated by Django 6.0.5 on 2026-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0002_rename_skills_used_project_skills_job_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jac.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jac.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='domains',
            field=models.ManyToManyField(blank=True, to='jac.domain'),
        ),
        migrations.AddField(
            model_name='project',
            name='domains',
            field=models.ManyToManyField(blank=True, to='jac.domain'),
        ),
        migrations.AddField(
            model_name='skill',
            name='domains',
            field=models.ManyToManyField(blank=True, to='jac.domain'),
        ),
    ]
