# Generated by Django 6.0.7 on 2026-07-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0002_generationrun_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='letter_focus',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='letter_tone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.DeleteModel(
            name='ResumeSnippet',
        ),
    ]
