# Generated by Django 6.0.5 on 2026-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0003_jobposting_jobpostaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesnippet',
            name='language',
            field=models.CharField(default='en', max_length=8),
        ),
    ]
