# Generated by Django 6.0.7 on 2026-07-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0003_generationrun_letter_focus_generationrun_letter_tone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='application_attachments')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jac.jobapplication')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
