# Generated by Django 6.0.5 on 2026-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0003_domain_alter_job_skills_alter_project_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='first_used',
            field=models.DateField(blank=True, null=True),
        ),
    ]
