# Generated by Django 6.0.5 on 2026-06-25 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0004_resumesnippet_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_text', models.TextField()),
                ('grade', models.CharField(default='light', max_length=10)),
                ('alias', models.CharField(default='default', max_length=100)),
                ('verify_grounding', models.BooleanField(default=True)),
                ('verifier_alias', models.CharField(blank=True, max_length=100)),
                ('personal_paragraph', models.BooleanField(default=True)),
                ('research_alias', models.CharField(blank=True, max_length=100)),
                ('max_body_snippets', models.PositiveSmallIntegerField(default=5)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('started', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('min_skill_proficiency', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('stage', models.CharField(blank=True, max_length=80)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_runs', to='jac.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
