# Generated by Django 6.0.7 on 2026-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0005_jobapplication_attachments_cvattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='sections_off',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
