# Generated by Django 6.0.5 on 2026-06-02 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0005_location_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain / Industry', 'verbose_name_plural': 'Domains / Industries'},
        ),
        migrations.AddField(
            model_name='domain',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(models.F('user'), models.F('name'), name='unique_domain_per_user'),
        ),
    ]
