# Generated by Django 6.0.5 on 2026-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0006_alter_domain_options_domain_user_alter_location_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
