# Generated by Django 6.0.5 on 2026-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0006_applicationlayout_jobapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrun',
            name='grade',
            field=models.CharField(choices=[('light', 'Light'), ('standard', 'Standard'), ('strong', 'Strong')], default='light', max_length=10),
        ),
    ]
