# Generated by Django 6.0.7 on 2026-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0006_jobapplication_sections_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No degree'), (1, 'Vocational / Ausbildung'), (2, 'Bachelor'), (3, 'Master / Diplom / Magister / Staatsexamen'), (4, 'Doctorate')], default=0),
        ),
    ]
