# Generated by Django 6.0.7 on 2026-08-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0007_education_completed_education_degree_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='completed',
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No degree'), (1, 'Abitur / High School'), (2, 'Vocational / Ausbildung'), (3, 'Bachelor'), (4, 'Master / Diplom / Magister / Staatsexamen'), (5, 'Doctorate')], default=0),
        ),
    ]
