# Generated by Django 6.0.5 on 2026-06-10 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0007_alter_domain_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='related_skills',
            field=models.ManyToManyField(blank=True, to='jac.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_of_experience_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResumeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('kind', models.CharField(choices=[('intro', 'Introduction'), ('achievement', 'Achievement'), ('value_statement', 'Value statement'), ('closing', 'Closing'), ('other', 'Other')], default='other', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(blank=True, to='jac.domain')),
                ('skills', models.ManyToManyField(blank=True, to='jac.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
    ]
