# Generated by Django 6.0.5 on 2026-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0007_alter_generationrun_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='task_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
