# Generated by Django 6.0.5 on 2026-06-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0008_skill_related_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='domains',
            field=models.ManyToManyField(blank=True, to='jac.domain'),
        ),
        migrations.AddField(
            model_name='certification',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='jac.skill'),
        ),
        migrations.AddField(
            model_name='education',
            name='domains',
            field=models.ManyToManyField(blank=True, to='jac.domain'),
        ),
        migrations.AddField(
            model_name='education',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jac.skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='jac.job'),
        ),
        migrations.AddField(
            model_name='resumesnippet',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_snippets', to='jac.job'),
        ),
        migrations.AddField(
            model_name='resumesnippet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_snippets', to='jac.project'),
        ),
        migrations.AddField(
            model_name='skill',
            name='builds_on',
            field=models.ManyToManyField(blank=True, related_name='enables', to='jac.skill'),
        ),
    ]
