# Generated by Django 6.0.5 on 2026-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0008_generationrun_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='letter_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
