# Generated by Django 6.0.5 on 2026-07-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0009_jobapplication_letter_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrun',
            name='max_body_snippets',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
