# Generated by Django 6.0.5 on 2026-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jac', '0010_alter_generationrun_max_body_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('manual', 'Manual / download')], max_length=8),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='response_outcome',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('other', 'Other')], max_length=12),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sent_by_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('follow_up', 'Follow-up sent'), ('response', 'Response from Posting'), ('inactive', 'Inactive')], default='draft', max_length=12),
        ),
    ]
