# Generated by Django 6.0.7 on 2026-07-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_messages', models.JSONField()),
                ('response_text', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('google', 'Google'), ('custom', 'Custom (OpenAI-compatible HTTP)'), ('ollama', 'Ollama (native /api/chat)')], max_length=32)),
                ('model', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('max_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Provider-specific extras forwarded to the adapter, e.g. {"reasoning_effort": "medium"} or {"think": false}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'alias'],
                'unique_together': {('user', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='LLMGradePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(choices=[('light', 'Light'), ('standard', 'Standard'), ('strong', 'Strong')], max_length=10)),
                ('alias', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_grade_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'strength'],
                'unique_together': {('user', 'strength')},
            },
        ),
    ]
