# Generated by Django 6.0.5 on 2026-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmrequestlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
