# Generated by Django 6.0.5 on 2026-07-14 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_connector', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMGradePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(choices=[('light', 'Light'), ('standard', 'Standard'), ('strong', 'Strong')], max_length=10)),
                ('alias', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_grade_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'strength'],
                'unique_together': {('user', 'strength')},
            },
        ),
    ]
