# Generated by Django 6.0.5 on 2026-05-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_connector', '0002_alter_llmrequestlog_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmrequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_request_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('google', 'Google'), ('custom', 'Custom (OpenAI-compatible HTTP)')], max_length=32)),
                ('model', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('max_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Provider-specific extras forwarded to the adapter, e.g. {"reasoning_effort": "medium"} or {"think": false}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'alias'],
                'unique_together': {('user', 'alias')},
            },
        ),
    ]
