/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthRequestResetRouteImport } from './routes/auth/request-reset'
import { Route as AuthMfaChallengeRouteImport } from './routes/auth/mfa-challenge'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedCvRouteImport } from './routes/_authenticated/cv'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCvIndexRouteImport } from './routes/_authenticated/cv/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthResetPasswordKeyRouteImport } from './routes/auth/reset-password.$key'
import { Route as AuthenticatedCvSkillsRouteImport } from './routes/_authenticated/cv/skills'
import { Route as AuthenticatedCvProjectsRouteImport } from './routes/_authenticated/cv/projects'
import { Route as AuthenticatedCvLanguagesRouteImport } from './routes/_authenticated/cv/languages'
import { Route as AuthenticatedCvJobsRouteImport } from './routes/_authenticated/cv/jobs'
import { Route as AuthenticatedCvEducationRouteImport } from './routes/_authenticated/cv/education'
import { Route as AuthenticatedCvCertificationsRouteImport } from './routes/_authenticated/cv/certifications'
import { Route as AuthenticatedCvAttachmentsRouteImport } from './routes/_authenticated/cv/attachments'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications/$applicationId'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account/security'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'
import { Route as AuthenticatedAccountPersonalityRouteImport } from './routes/_authenticated/account/personality'
import { Route as AuthenticatedAccountLlmRouteImport } from './routes/_authenticated/account/llm'
import { Route as AuthenticatedAccountEmailRouteImport } from './routes/_authenticated/account/email'
import { Route as AuthenticatedAccountDangerRouteImport } from './routes/_authenticated/account/danger'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRequestResetRoute = AuthRequestResetRouteImport.update({
  id: '/request-reset',
  path: '/request-reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMfaChallengeRoute = AuthMfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedCvRoute = AuthenticatedCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCvIndexRoute = AuthenticatedCvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCvRoute,
} as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthResetPasswordKeyRoute = AuthResetPasswordKeyRouteImport.update({
  id: '/reset-password/$key',
  path: '/reset-password/$key',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedCvSkillsRoute = AuthenticatedCvSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedCvRoute,
} as any)
const AuthenticatedCvProjectsRoute = AuthenticatedCvProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedCvRoute,
} as any)
const AuthenticatedCvLanguagesRoute =
  AuthenticatedCvLanguagesRouteImport.update({
    id: '/languages',
    path: '/languages',
    getParentRoute: () => AuthenticatedCvRoute,
  } as any)
const AuthenticatedCvJobsRoute = AuthenticatedCvJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedCvRoute,
} as any)
const AuthenticatedCvEducationRoute =
  AuthenticatedCvEducationRouteImport.update({
    id: '/education',
    path: '/education',
    getParentRoute: () => AuthenticatedCvRoute,
  } as any)
const AuthenticatedCvCertificationsRoute =
  AuthenticatedCvCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => AuthenticatedCvRoute,
  } as any)
const AuthenticatedCvAttachmentsRoute =
  AuthenticatedCvAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => AuthenticatedCvRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountPersonalityRoute =
  AuthenticatedAccountPersonalityRouteImport.update({
    id: '/personality',
    path: '/personality',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountLlmRoute = AuthenticatedAccountLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AuthenticatedAccountRoute,
} as any)
const AuthenticatedAccountEmailRoute =
  AuthenticatedAccountEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountDangerRoute =
  AuthenticatedAccountDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/explore': typeof ExploreRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/cv': typeof AuthenticatedCvRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa-challenge': typeof AuthMfaChallengeRoute
  '/auth/request-reset': typeof AuthRequestResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/account/danger': typeof AuthenticatedAccountDangerRoute
  '/account/email': typeof AuthenticatedAccountEmailRoute
  '/account/llm': typeof AuthenticatedAccountLlmRoute
  '/account/personality': typeof AuthenticatedAccountPersonalityRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/cv/attachments': typeof AuthenticatedCvAttachmentsRoute
  '/cv/certifications': typeof AuthenticatedCvCertificationsRoute
  '/cv/education': typeof AuthenticatedCvEducationRoute
  '/cv/jobs': typeof AuthenticatedCvJobsRoute
  '/cv/languages': typeof AuthenticatedCvLanguagesRoute
  '/cv/projects': typeof AuthenticatedCvProjectsRoute
  '/cv/skills': typeof AuthenticatedCvSkillsRoute
  '/auth/reset-password/$key': typeof AuthResetPasswordKeyRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/cv/': typeof AuthenticatedCvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/explore': typeof ExploreRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa-challenge': typeof AuthMfaChallengeRoute
  '/auth/request-reset': typeof AuthRequestResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/account/danger': typeof AuthenticatedAccountDangerRoute
  '/account/email': typeof AuthenticatedAccountEmailRoute
  '/account/llm': typeof AuthenticatedAccountLlmRoute
  '/account/personality': typeof AuthenticatedAccountPersonalityRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/cv/attachments': typeof AuthenticatedCvAttachmentsRoute
  '/cv/certifications': typeof AuthenticatedCvCertificationsRoute
  '/cv/education': typeof AuthenticatedCvEducationRoute
  '/cv/jobs': typeof AuthenticatedCvJobsRoute
  '/cv/languages': typeof AuthenticatedCvLanguagesRoute
  '/cv/projects': typeof AuthenticatedCvProjectsRoute
  '/cv/skills': typeof AuthenticatedCvSkillsRoute
  '/auth/reset-password/$key': typeof AuthResetPasswordKeyRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/cv': typeof AuthenticatedCvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/explore': typeof ExploreRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/cv': typeof AuthenticatedCvRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa-challenge': typeof AuthMfaChallengeRoute
  '/auth/request-reset': typeof AuthRequestResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/_authenticated/account/danger': typeof AuthenticatedAccountDangerRoute
  '/_authenticated/account/email': typeof AuthenticatedAccountEmailRoute
  '/_authenticated/account/llm': typeof AuthenticatedAccountLlmRoute
  '/_authenticated/account/personality': typeof AuthenticatedAccountPersonalityRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/_authenticated/cv/attachments': typeof AuthenticatedCvAttachmentsRoute
  '/_authenticated/cv/certifications': typeof AuthenticatedCvCertificationsRoute
  '/_authenticated/cv/education': typeof AuthenticatedCvEducationRoute
  '/_authenticated/cv/jobs': typeof AuthenticatedCvJobsRoute
  '/_authenticated/cv/languages': typeof AuthenticatedCvLanguagesRoute
  '/_authenticated/cv/projects': typeof AuthenticatedCvProjectsRoute
  '/_authenticated/cv/skills': typeof AuthenticatedCvSkillsRoute
  '/auth/reset-password/$key': typeof AuthResetPasswordKeyRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/cv/': typeof AuthenticatedCvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/account'
    | '/applications'
    | '/cv'
    | '/auth/login'
    | '/auth/mfa-challenge'
    | '/auth/request-reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/portfolio/$slug'
    | '/account/danger'
    | '/account/email'
    | '/account/llm'
    | '/account/personality'
    | '/account/profile'
    | '/account/security'
    | '/applications/$applicationId'
    | '/cv/attachments'
    | '/cv/certifications'
    | '/cv/education'
    | '/cv/jobs'
    | '/cv/languages'
    | '/cv/projects'
    | '/cv/skills'
    | '/auth/reset-password/$key'
    | '/applications/'
    | '/cv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/account'
    | '/auth/login'
    | '/auth/mfa-challenge'
    | '/auth/request-reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/portfolio/$slug'
    | '/account/danger'
    | '/account/email'
    | '/account/llm'
    | '/account/personality'
    | '/account/profile'
    | '/account/security'
    | '/applications/$applicationId'
    | '/cv/attachments'
    | '/cv/certifications'
    | '/cv/education'
    | '/cv/jobs'
    | '/cv/languages'
    | '/cv/projects'
    | '/cv/skills'
    | '/auth/reset-password/$key'
    | '/applications'
    | '/cv'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/explore'
    | '/_authenticated/account'
    | '/_authenticated/applications'
    | '/_authenticated/cv'
    | '/auth/login'
    | '/auth/mfa-challenge'
    | '/auth/request-reset'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/portfolio/$slug'
    | '/_authenticated/account/danger'
    | '/_authenticated/account/email'
    | '/_authenticated/account/llm'
    | '/_authenticated/account/personality'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/security'
    | '/_authenticated/applications/$applicationId'
    | '/_authenticated/cv/attachments'
    | '/_authenticated/cv/certifications'
    | '/_authenticated/cv/education'
    | '/_authenticated/cv/jobs'
    | '/_authenticated/cv/languages'
    | '/_authenticated/cv/projects'
    | '/_authenticated/cv/skills'
    | '/auth/reset-password/$key'
    | '/_authenticated/applications/'
    | '/_authenticated/cv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/request-reset': {
      id: '/auth/request-reset'
      path: '/request-reset'
      fullPath: '/auth/request-reset'
      preLoaderRoute: typeof AuthRequestResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/mfa-challenge': {
      id: '/auth/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/auth/mfa-challenge'
      preLoaderRoute: typeof AuthMfaChallengeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/cv': {
      id: '/_authenticated/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AuthenticatedCvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cv/': {
      id: '/_authenticated/cv/'
      path: '/'
      fullPath: '/cv/'
      preLoaderRoute: typeof AuthenticatedCvIndexRouteImport
      parentRoute: typeof AuthenticatedCvRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/auth/reset-password/$key': {
      id: '/auth/reset-password/$key'
      path: '/reset-password/$key'
      fullPath: '/auth/reset-password/$key'
      preLoaderRoute: typeof AuthResetPasswordKeyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/cv/skills': {
      id: '/_authenticated/cv/skills'
      path: '/skills'
      fullPath: '/cv/skills'
      preLoaderRoute: typeof AuthenticatedCvSkillsRouteImport
      parentRoute: typeof AuthenticatedCvRoute
    }
    '/_authenticated/cv/projects': {
      id: '/_authenticated/cv/projects'
      path: '/projects'
      fullPath: '/cv/projects'
      preLoaderRoute: typeof AuthenticatedCvProjectsRouteImport
      parentRoute: typeof AuthenticatedCvRoute
    }
    '/_authenticated/cv/languages': {
      id: '/_authenticated/cv/languages'
      path: '/languages'
      fullPath: '/cv/languages'
      preLoaderRoute: typeof AuthenticatedCvLanguagesRouteImport
      parentRoute: typeof AuthenticatedCvRoute
    }
    '/_authenticated/cv/jobs': {
      id: '/_authenticated/cv/jobs'
      path: '/jobs'
      fullPath: '/cv/jobs'
      preLoaderRoute: typeof AuthenticatedCvJobsRouteImport
      parentRoute: typeof AuthenticatedCvRoute
    }
    '/_authenticated/cv/education': {
      id: '/_authenticated/cv/education'
      path: '/education'
      fullPath: '/cv/education'
      preLoaderRoute: typeof AuthenticatedCvEducationRouteImport
      parentRoute: typeof AuthenticatedCvRoute
    }
    '/_authenticated/cv/certifications': {
      id: '/_authenticated/cv/certifications'
      path: '/certifications'
      fullPath: '/cv/certifications'
      preLoaderRoute: typeof AuthenticatedCvCertificationsRouteImport
      parentRoute: typeof AuthenticatedCvRoute
    }
    '/_authenticated/cv/attachments': {
      id: '/_authenticated/cv/attachments'
      path: '/attachments'
      fullPath: '/cv/attachments'
      preLoaderRoute: typeof AuthenticatedCvAttachmentsRouteImport
      parentRoute: typeof AuthenticatedCvRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/account/security': {
      id: '/_authenticated/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/personality': {
      id: '/_authenticated/account/personality'
      path: '/personality'
      fullPath: '/account/personality'
      preLoaderRoute: typeof AuthenticatedAccountPersonalityRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/llm': {
      id: '/_authenticated/account/llm'
      path: '/llm'
      fullPath: '/account/llm'
      preLoaderRoute: typeof AuthenticatedAccountLlmRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/email': {
      id: '/_authenticated/account/email'
      path: '/email'
      fullPath: '/account/email'
      preLoaderRoute: typeof AuthenticatedAccountEmailRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/danger': {
      id: '/_authenticated/account/danger'
      path: '/danger'
      fullPath: '/account/danger'
      preLoaderRoute: typeof AuthenticatedAccountDangerRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountDangerRoute: typeof AuthenticatedAccountDangerRoute
  AuthenticatedAccountEmailRoute: typeof AuthenticatedAccountEmailRoute
  AuthenticatedAccountLlmRoute: typeof AuthenticatedAccountLlmRoute
  AuthenticatedAccountPersonalityRoute: typeof AuthenticatedAccountPersonalityRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountDangerRoute: AuthenticatedAccountDangerRoute,
  AuthenticatedAccountEmailRoute: AuthenticatedAccountEmailRoute,
  AuthenticatedAccountLlmRoute: AuthenticatedAccountLlmRoute,
  AuthenticatedAccountPersonalityRoute: AuthenticatedAccountPersonalityRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsApplicationIdRoute:
      AuthenticatedApplicationsApplicationIdRoute,
    AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedCvRouteChildren {
  AuthenticatedCvAttachmentsRoute: typeof AuthenticatedCvAttachmentsRoute
  AuthenticatedCvCertificationsRoute: typeof AuthenticatedCvCertificationsRoute
  AuthenticatedCvEducationRoute: typeof AuthenticatedCvEducationRoute
  AuthenticatedCvJobsRoute: typeof AuthenticatedCvJobsRoute
  AuthenticatedCvLanguagesRoute: typeof AuthenticatedCvLanguagesRoute
  AuthenticatedCvProjectsRoute: typeof AuthenticatedCvProjectsRoute
  AuthenticatedCvSkillsRoute: typeof AuthenticatedCvSkillsRoute
  AuthenticatedCvIndexRoute: typeof AuthenticatedCvIndexRoute
}

const AuthenticatedCvRouteChildren: AuthenticatedCvRouteChildren = {
  AuthenticatedCvAttachmentsRoute: AuthenticatedCvAttachmentsRoute,
  AuthenticatedCvCertificationsRoute: AuthenticatedCvCertificationsRoute,
  AuthenticatedCvEducationRoute: AuthenticatedCvEducationRoute,
  AuthenticatedCvJobsRoute: AuthenticatedCvJobsRoute,
  AuthenticatedCvLanguagesRoute: AuthenticatedCvLanguagesRoute,
  AuthenticatedCvProjectsRoute: AuthenticatedCvProjectsRoute,
  AuthenticatedCvSkillsRoute: AuthenticatedCvSkillsRoute,
  AuthenticatedCvIndexRoute: AuthenticatedCvIndexRoute,
}

const AuthenticatedCvRouteWithChildren = AuthenticatedCvRoute._addFileChildren(
  AuthenticatedCvRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedCvRoute: typeof AuthenticatedCvRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedCvRoute: AuthenticatedCvRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaChallengeRoute: typeof AuthMfaChallengeRoute
  AuthRequestResetRoute: typeof AuthRequestResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthResetPasswordKeyRoute: typeof AuthResetPasswordKeyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaChallengeRoute: AuthMfaChallengeRoute,
  AuthRequestResetRoute: AuthRequestResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthResetPasswordKeyRoute: AuthResetPasswordKeyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ExploreRoute: ExploreRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
